engine = "ffmpeg"
danmu = true
outputFolder = "E:/record/test/{streamer}/%yyyy-%MM-%dd"
outputFileName = "%HH_%mm_%ss-{title}"
outputFileFormat = "mp4"
# global flag to enable/disable delete files after upload
# READ CAREFULLY! rclone command (using callback) is considered as an upload operation
# READ CAREFULLY! rclone command (using callback) is considered as an upload operation
# READ CAREFULLY! rclone command (using callback) is considered as an upload operation
deleteFilesAfterUpload = false
# minimum size to be considered as a streaming data (default to 20 MB)
minPartSize = 10000000
#maxPartSize = 26214400
# maximum duration (seconds) of a download part file (default to 1 hour)
maxPartDuration = 5400
# maximum number of download coroutines
maxConcurrentDownloads = 5
maxConcurrentUploads = 3
# maximum number of download retries
maxDownloadRetries = 3
# delay between download retries
downloadRetryDelay = 20

[huyaConfig]
primaryCdn = "HW"
maxBitRate = 10000

[douyinConfig]
cookies = "ttwid=1%7CNFM7mouxA2Ho_OoJecIChApUtSAZfKdJJH9JxmeT6t0%7C1707437548%7Ccc85bb46fc5cb2588a1deb29fa8d3ae69128a81e2ca56b4d52aa790c8bad8124; __ac_nonce=065ccd1170073d3993c76; __ac_signature=_02B4Z6wo00f01Biv0CgAAIDBhDRj5YfVxhQYj9SAAGPtd5J9Vyrip2g1oCp6fmDKfL6QQ1WrM.OEcDcyG55yWOr4foKQSQLMz-kbNnuvZturUNX1RCkqL5uWkeXmAXglDEmJdmb.W0QdW.qCa4; "
quality = "origin"

[[streamers]]
name = "微竞-浪D"
url = "https://www.huya.com/196645"
isActivated = true
[streamers.downloadConfig]
type = "huya"

[[streamers]]
name = "DANK1NG"
url = "https://www.huya.com/dank1ng"
isActivated = true
[streamers.downloadConfig]
type = "huya"
#danmu = true
# callback to execute when a parted download is finished
#[[streamers.downloadConfig.onPartedDownload]]
## callback type, possible values: "rclone", "command"
#type = "rclone"
## whether to enable the callback (default to false)
#enabled = true
## rclone operation type, possible values: "copy", "move", ...
#rcloneOperation = "copy"
## rclone remote name
## possible placeholder values: "{title}", "{streamer}", "%yyyy", "%MM", "%dd", "%HH", "%mm", "%ss"
#remotePath = "onedrive:records/{streamer}/%yyyy-%MM-%dd"
## rclone args
#args = [
#    #    "--config",
#    #    "/opt/rclone.conf",
#    "-P",
#    "--onedrive-chunk-size",
#    "100M"
#]

[[streamers]]
name = "雪乃荔荔枝"
url = "https://www.huya.com/273493"
isActivated = true
[streamers.downloadConfig]
type = "huya"
#danmu = true
#outputFileExtension = "mp4"
#[[streamers.downloadConfig.onPartedDownload]]
## callback type, possible values: "rclone", "command"
#type = "rclone"
## whether to enable the callback (default to false)
#enabled = true
## rclone operation type, possible values: "copy", "move", ...
#rcloneOperation = "copy"
## rclone remote name
## possible placeholder values: "{title}", "{streamer}", "%yyyy", "%MM", "%dd", "%HH", "%mm", "%ss"
#remotePath = "onedrive:records/{streamer}/%yyyy-%MM-%dd"
## rclone args
#args = [
#    #    "--config",
#    #    "/opt/rclone.conf",
#    "-P",
#    "--onedrive-chunk-size",
#    "100M"
#]

[[streamers]]
name = "杰米GEmini"
url = "https://www.huya.com/geminiii"
[streamers.downloadConfig]
type = "huya"
danmu = true
#outputFileExtension = "mp4"
#[[streamers.downloadConfig.onPartedDownload]]
## callback type, possible values: "rclone", "command"
#type = "rclone"
## whether to enable the callback (default to false)
#enabled = true
## rclone operation type, possible values: "copy", "move", ...
#rcloneOperation = "copy"
## rclone remote name
## possible placeholder values: "{title}", "{streamer}", "%yyyy", "%MM", "%dd", "%HH", "%mm", "%ss"
#remotePath = "onedrive:records/{streamer}/%yyyy-%MM-%dd"
## rclone args
#args = [
#    #    "--config",
#    #    "/opt/rclone.conf",
#    "-P",
#    "--onedrive-chunk-size",
#    "100M"
#]


[[streamers]]
name = "企鹅 (无畏契约)"
url = "https://live.douyin.com/386003334438"
[streamers.downloadConfig]
type = "douyin"
#outputFileExtension = "mp4"
#[[streamers.downloadConfig.onPartedDownload]]
## callback type, possible values: "rclone", "command"
#type = "rclone"
## rclone operation type, possible values: "copy", "move", ...
#rcloneOperation = "copy"
## whether to enable the callback (default to false)
#enabled = true
## rclone remote name
## possible placeholder values: "{title}", "{streamer}", "%yyyy", "%MM", "%dd", "%HH", "%mm", "%ss"
#remotePath = "onedrive:records/{streamer}/%yyyy-%MM-%dd"
## rclone args
#args = [
#    #    "--config",
#    #    "/opt/rclone.conf",
#    "-P",
#    "--onedrive-chunk-size",
#    "100M"
#]

[[streamers]]
name = "简单咩一下"
url = "https://live.douyin.com/217536353956"

[streamers.downloadConfig]
type = "douyin"
#[[streamers.downloadConfig.onPartedDownload]]
## callback type, possible values: "rclone", "command"
#type = "rclone"
## whether to enable the callback (default to false)
#enabled = true
## rclone operation type, possible values: "copy", "move", ...
#rcloneOperation = "copy"
## rclone remote name
## possible placeholder values: "{title}", "{streamer}", "%yyyy", "%MM", "%dd", "%HH", "%mm", "%ss"
#remotePath = "onedrive:records/{streamer}/%yyyy-%MM-%dd"
## rclone args
#args = [
#    #    "--config",
#    #    "/opt/rclone.conf",
#    "-P",
#    "--onedrive-chunk-size",
#    "100M"
#]

[[streamers]]
name = "小羊仔（无畏契约）"
url = "https://live.douyin.com/66407121168"
isActivated = true
[streamers.downloadConfig]
type = "douyin"
#outputFileExtension = "mp4"
#[[streamers.downloadConfig.onPartedDownload]]
## callback type, possible values: "rclone", "command"
#type = "rclone"
## whether to enable the callback (default to false)
#enabled = true
## rclone operation type, possible values: "copy", "move", ...
#rcloneOperation = "copy"
## rclone remote name
## possible placeholder values: "{title}", "{streamer}", "%yyyy", "%MM", "%dd", "%HH", "%mm", "%ss"
#remotePath = "onedrive:records/{streamer}/%yyyy-%MM-%dd"
## rclone args
#args = [
#    #    "--config",
#    #    "/opt/rclone.conf",
#    "-P",
#    "--onedrive-chunk-size",
#    "100M"
#]


[[streamers]]
name = "黄大楼"
url = "https://live.douyin.com/848175761759"
isActivated = true
[streamers.downloadConfig]
type = "douyin"
#outputFileExtension = "mp4"
#[[streamers.downloadConfig.onPartedDownload]]
## callback type, possible values: "rclone", "command"
#type = "rclone"
## whether to enable the callback (default to false)
#enabled = true
## rclone operation type, possible values: "copy", "move", ...
#rcloneOperation = "copy"
## rclone remote name
## possible placeholder values: "{title}", "{streamer}", "%yyyy", "%MM", "%dd", "%HH", "%mm", "%ss"
#remotePath = "onedrive:records/{streamer}/%yyyy-%MM-%dd"
## rclone args
#args = [
#    #    "--config",
#    #    "/opt/rclone.conf",
#    "-P",
#    "--onedrive-chunk-size",
#    "100M"
#]